### ISSUE TITLE
Multiple DBs on same server

### ISSUE THREAD

**Issue by sstraus** [mocleiri/device-code-sql-server-driver#1]
First I what to thank you for saving Datagrip on Azure and MFA.
Do you know how to target multiple DBs on the same server?

**Comment by mocleiri** [comment]
@sstraus

This should work for client credentials and device code flow.  I'm running separate configuration files for each database.

For example I would have two copies of a db.properties file, db1.properties and db2.properties and then two data sources setup in Datagrip.  With the advanced tab having a single propertiesFile entry where the value was the absolute path to the configuration file.

```
clientId=<< client id >>
# if this is logging in using the app registration identity specify the secret
#clientSecret= << client Secret >>
# if this is device code login then omit the secret and the token will be in the identiy of the mfa user.
tenantId=<< azure tenant id >>
database=<< database name >>
server=<< managed instance/sql server name >>
hostNameInCertificate=*.should-match-server-host-name.database.windows.net
```

I just tried it.  So long as the identity you have is permissioned to be able to access the multiple databases,  Then using the grey outline boxes on the right hand side to show more databases and then a particular schema within those selected databases.

![image](https://user-images.githubusercontent.com/250942/87823709-eb0abb80-c841-11ea-9a80-fc5b6d478d1f.png)

**Comment by mocleiri** [comment]
Closing as it's possible in two ways:

- Use a configuration file per identity and database.
- Permission the identity to access multiple databases.  Pick 1 for the configuration file but use the filters to expose the others.  

It's supposed to be able to make cross DB joins in an Azure MI and the second option would be the way to support that case in datagrip.
